services:
  db:
    image: mysql:8.0
    container_name: mysql_db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: dringgo
      MYSQL_USER: dringgo
      MYSQL_PASSWORD: dringgo
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql

  backend:
    build:
      context: ./backend
    container_name: backend
    ports:
      - "3000:3000"
    volumes:
      - ./backend:/app
      # Exclure `node_modules` de l'hôte pour éviter des conflits
      - /app/node_modules
    depends_on:
      - db

  frontend:
    build:
      context: ./frontend
    container_name: frontend
    ports:
      - "5173:5173"
    volumes:
      - ./frontend:/app
      # Exclure `node_modules` de l'hôte pour éviter des conflits
      - /app/node_modules
    depends_on:
      - backend

volumes:
  db_data:
