services:
  - type: web
    name: dringgo-backend
    env: docker
    plan: free
    dockerfilePath: ./backend/Dockerfile
    buildCommand: ""
    startCommand: ""
    envVars:
      - key: DB_HOST
        value: mysql_db
      - key: DB_USER
        value: dringgo
      - key: DB_PASSWORD
        value: dringgo
      - key: DB_NAME
        value: dringgo

  - type: web
    name: dringgo-frontend
    env: docker
    plan: free
    dockerfilePath: ./frontend/Dockerfile
    buildCommand: ""
    startCommand: ""
    envVars:
      - key: FRONTEND_URL
        value: https://dringgo-backend.onrender.com
