services:
  - type: web
    name: mysql-db
    env: docker
    plan: free
    image: mysql:8.0  # Utilisation de l'image officielle de MySQL
    envVars:
      - key: MYSQL_ROOT_PASSWORD
        value: root
      - key: MYSQL_DATABASE
        value: dringgo
      - key: MYSQL_USER
        value: dringgo
      - key: MYSQL_PASSWORD
        value: dringgo
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql

  - type: web
    name: dringgo-backend
    env: docker
    plan: free
    dockerfilePath: ./backend/Dockerfile
    buildCommand: "" 
    startCommand: ""
    envVars:
      - key: DB_HOST
        value: mysql-db
      - key: DB_USER
        value: dringgo
      - key: DB_PASSWORD
        value: dringgo
      - key: DB_NAME
        value: dringgo

  - type: web
    name: dringgo-frontend
    env: docker
    plan: free
    dockerfilePath: ./frontend/Dockerfile
    buildCommand: "" 
    startCommand: ""
    envVars:
      - key: FRONTEND_URL
        value: https://dringgo-backend.onrender.com

volumes:
  db_data:
