services:
  - type: web
    name: dringgo-backend
    env: docker
    plan: free
    dockerfilePath: ./backend/Dockerfile
    buildCommand: "npm install"  
    startCommand: "npm start"
    envVars:
      - key: DB_HOST
        value: mysql_db
      - key: DB_USER
        value: dringgo
      - key: DB_PASSWORD
        value: your_mysql_password
      - key: DB_NAME
        value: dringgo
